version: 2.1
jobs:
  build:
    docker:
      - image: circleci/maven@1.2.0# the primary container, where your job's commands are run
  
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world"
      
